name: Build and Package KMM Project

on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:
    branches:
      - main
      - develop

jobs:
  android-build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bustlespot_android_debug
          path: /home/runner/work/Bustlespot-KMM/Bustlespot-KMM/composeApp/build/outputs/apk/debug/composeApp-debug.apk

      - name: Download Android Debug APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: bustlespot_android_debug
          path: downloaded_artifacts


      - name: Run Android Unit Tests
        run: ./gradlew testDebugUnitTest

  ios-build:
    name: Build iOS
    runs-on: macos-latest
    needs: android-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build iOS Framework
        run: ./gradlew linkDebugFrameworkIosSimulator

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bustlespot_android_debug
          path: /Users/runner/work/Bustlespot-KMM/Bustlespot-KMM/composeApp/build/outputs/apk/debug/composeApp-debug.apk

      - name: Download Android Debug APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: bustlespot_android_debug
          path: downloaded_android_debug_artifacts

      - name: Run iOS Unit Tests
        run: ./gradlew iosX64Test

  dmg-build:
    name: Package DMG
    runs-on: macos-latest
    needs: ios-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build DMG Package
        run: ./gradlew packageDMG
        # Ensure assembleDMG task creates a DMG file (e.g., build/distributions/MyApp.dmg)

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bustlespot_macos
          path: /Users/runner/work/Bustlespot-KMM/Bustlespot-KMM/composeApp/build/compose/binaries/main/dmg/Bustlespot-KMM-1.0.0.dmg

      - name: Download DMG Artifact
        uses: actions/download-artifact@v4
        with:
          name: bustlespot_macos
          path: downloaded_macos_artifacts

  msi-build:
    name: Package MSI
    runs-on: windows-latest
    needs: android-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build MSI Package
        run: .\gradlew packageMSI
        # Ensure assembleMSI task creates an MSI file (e.g., build/distributions/MyApp.msi)

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bustlespot_windows
          path: D:\a\Bustlespot-KMM\Bustlespot-KMM\composeApp\build\compose\binaries\main\msi\Bustlespot-KMM-1.0.0.msi

      - name: Download MSI Artifact
        uses: actions/download-artifact@v4
        with:
          name: bustlespot_windows
          path: downloaded_windows_artifacts

  deb-build:
    name: Package DEB
    runs-on: ubuntu-latest
    needs: android-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build DEB Package
        run: ./gradlew packageDEB
        # Ensure assembleDEB task creates a DEB file (e.g., build/distributions/MyApp.deb)

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bustlespot_linux
          path: /home/runner/work/Bustlespot-KMM/Bustlespot-KMM/composeApp/build/compose/binaries/main/deb/bustlespot-kmm_1.0.0-1.0.0_amd64.deb

      - name: Download DEB Artifact
        uses: actions/download-artifact@v4
        with:
          name: bustlespot_linux
          path: downloaded_linux_artifacts